-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 13, 2020 at 06:36 AM
-- Server version: 10.4.14-MariaDB
-- PHP Version: 7.2.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mydatabase`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `desc` text NOT NULL,
  `price` decimal(7,2) NOT NULL,
  `rrp` decimal(7,2) NOT NULL DEFAULT 0.00,
  `quantity` int(11) NOT NULL,
  `img` text CHARACTER SET latin1 NOT NULL,
  `date_added` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `desc`, `price`, `rrp`, `quantity`, `img`, `date_added`) VALUES
(1, 'Palak', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '16.00', '0.00', 15, 'lal shakh.jpg', '0000-00-00 00:00:00'),
(2, 'Lemon', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '12.38', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000127_17-fresho-lemon.jpg', '0000-00-00 00:00:00'),
(3, 'Potato Onion Tomato 1 kg Each', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '115.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200045_1-fresho-potato-onion-tomato-1-kg-each.jpg', '0000-00-00 00:00:00'),
(4, 'Tomato - Hybrid', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '11.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000201_15-fresho-tomato-hybrid.jpg', '0000-00-00 00:00:00'),
(5, 'Coriander Leaves', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '16.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000097_19-fresho-coriander-leaves.jpg', '0000-00-00 00:00:00'),
(6, 'Cauliflower', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '14.85', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000074_19-fresho-cauliflower.jpg', '0000-00-00 00:00:00'),
(7, 'Mushrooms - Button', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '49.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000273_16-fresho-mushrooms-button.jpg', '0000-00-00 00:00:00'),
(8, 'Capsicum - Green', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '17.82', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000069_20-fresho-capsicum-green.jpg', '0000-00-00 00:00:00'),
(9, 'Tomato - Local, Organically Grown', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '13.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40022638_3-fresho-tomato-local-organically-grown.jpg', '0000-00-00 00:00:00'),
(10, 'Coconut - Medium', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '34.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000093_16-fresho-coconut-medium.jpg', '0000-00-00 00:00:00'),
(11, 'Tender Coconut - Medium', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '39.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40057966_2-fresho-tender-coconut-medium.jpg', '0000-00-00 00:00:00'),
(12, 'Pomegranate', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '299.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000268_27-fresho-pomegranate.jpg', '0000-00-00 00:00:00'),
(13, 'Pomegranate', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '229.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000269_28-fresho-pomegranate.jpg', '0000-00-00 00:00:00'),
(14, 'Tomato - Local', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '9.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000204_16-fresho-tomato-local.jpg', '0000-00-00 00:00:00'),
(15, 'Peanuts/Mungaphali - Raw', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '29.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/30010384_10-bb-popular-peanutsmungaphali-raw.jpg', '0000-00-00 00:00:00'),
(16, 'Pure Ghee', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '452.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/213273_7-nandini-pure-ghee.jpg', '0000-00-00 00:00:00'),
(17, 'Maida', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '72.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40044729_4-bb-royal-maida.jpg', '0000-00-00 00:00:00'),
(18, 'Sooji Ordinary/Bombay Rava', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '42.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000423_11-bb-royal-sooji-ordinarybombay-rava.jpg', '0000-00-00 00:00:00'),
(19, 'Almond/Badam - Californian, Giri', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '314.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000549_12-bb-popular-almondbadam-californian-giri.jpg', '0000-00-00 00:00:00'),
(20, 'Moong Dal', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '119.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/30005420_10-bb-popular-moong-dal.jpg', '0000-00-00 00:00:00'),
(21, 'Toor/Arhar Dal', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '121.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000428_16-bb-popular-toorarhar-dal.jpg', '0000-00-00 00:00:00'),
(22, 'Cashew/Kaju - Whole', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '429.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000551_9-bb-popular-cashewkaju-whole.jpg', '0000-00-00 00:00:00'),
(23, 'Iodized', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '20.79', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/241600_5-tata-salt-iodized.jpg', '0000-00-00 00:00:00'),
(24, 'Toor Dal/Arhar Dal - Desi', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '650.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40042841_6-bb-royal-toor-dalarhar-dal-desi.jpg', '0000-00-00 00:00:00'),
(25, 'Organic - Almond/Badam', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '499.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40101871_9-bb-royal-organic-almondbadam.jpg', '0000-00-00 00:00:00'),
(26, 'Poha/Avalakki/Aval/Chivda - Thick', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '47.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000431_17-bb-royal-pohaavalakkiavalchivda-thick.jpg', '0000-00-00 00:00:00'),
(27, 'Rice - Raw, Sona Masoori', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '1049.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/20001215_10-bb-popular-rice-raw-sona-masoori.jpg', '0000-00-00 00:00:00'),
(28, 'Superior Chakki Wheat Atta - Fortified', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '82.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1203711_1-bb-royal-superior-chakki-wheat-atta-fortified.jpg', '0000-00-00 00:00:00'),
(29, 'Toned Milk', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '48.51', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/100285703_15-nandini-goodlife-toned-milk.jpg', '0000-00-00 00:00:00'),
(30, 'Malai Paneer', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '74.25', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/279588_6-amul-malai-paneer.jpg', '0000-00-00 00:00:00'),
(31, 'Toned Milk', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '760.32', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200166_2-amul-taaza-toned-milk.jpg', '0000-00-00 00:00:00'),
(32, 'Whole Wheat Bread - Safe, Preservative Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '38.61', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40025355_6-fresho-whole-wheat-bread-safe-preservative-free.jpg', '0000-00-00 00:00:00'),
(33, 'Toned Milk', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '499.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/244999_1-nandini-goodlife-toned-milk.jpg', '0000-00-00 00:00:00'),
(34, 'Masti Buttermilk - Spice', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '11.88', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/161899_8-amul-masti-buttermilk-spice.jpg', '0000-00-00 00:00:00'),
(35, 'Cheese Slices', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '117.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/104808_7-amul-cheese-slices.jpg', '0000-00-00 00:00:00'),
(36, 'Bread - Whole Wheat, Chemical Free 400G + Eggs - Regular 6pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '83.61', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1204354_1-fresho-bread-whole-wheat-chemical-free-400g-eggs-regular-6pcs.jpg', '0000-00-00 00:00:00'),
(37, 'Sandwich Bread - Safe, Preservative Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '28.71', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40087525_2-fresho-sandwich-bread-safe-preservative-free.jpg', '0000-00-00 00:00:00'),
(38, 'Sandwich Bread - White, Chemical Free 400G + Eggs - Regular 6pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '83.61', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1204352_1-fresho-sandwich-bread-white-chemical-free-400g-eggs-regular-6pcs.jpg', '0000-00-00 00:00:00'),
(39, 'Bread - Brown, Chemical Free 400G + Eggs - Regular 6pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '83.61', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1204353_1-fresho-bread-brown-chemical-free-400g-eggs-regular-6pcs.jpg', '0000-00-00 00:00:00'),
(40, 'Natural Set Curd', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '196.02', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1209134_2-milky-mist-natural-set-curd.jpg', '0000-00-00 00:00:00'),
(41, 'Cheese - Mozzarella Pizza', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '105.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40003157_1-milky-mist-cheese-mozzarella-pizza.jpg', '0000-00-00 00:00:00'),
(42, 'Skimmed Milk', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '23.76', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/242673_1-nandini-goodlife-skimmed-milk.jpg', '0000-00-00 00:00:00'),
(43, 'Soft Drink', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '210.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208181_1-coca-cola-soft-drink.jpg', '0000-00-00 00:00:00'),
(44, 'Cothas Cold Coffee', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '217.50', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/186070_8-cothas-coffee-.jpg', '0000-00-00 00:00:00'),
(45, 'Drink - Fresh \'N\' Juicy Mango', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '9.40', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/274035_6-frooti-drink-fresh-n-juicy-mango.jpg', '0000-00-00 00:00:00'),
(46, 'Soft Drink', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '1596.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1212285_1-thums-up-soft-drink.jpg', '0000-00-00 00:00:00'),
(47, 'Masti Buttermilk - Spice', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '11.88', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/161899_8-amul-masti-buttermilk-spice.jpg', '0000-00-00 00:00:00'),
(48, 'Soda - Original Ginger Ale', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '297.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208190_1-schweppes-soda-original-ginger-ale.jpg', '0000-00-00 00:00:00'),
(49, 'Pro-Health Drink - Chocolate', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '514.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1204514_2-bournvita-pro-health-drink-chocolate.jpg', '0000-00-00 00:00:00'),
(50, 'Leaf Tea 1 kg + Leaf Tea 250 g', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '676.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1209750_2-tata-tea-gold-leaf-tea-1-kg-leaf-tea-250-g.jpg', '0000-00-00 00:00:00'),
(51, 'Probiotic Health Drink', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '277.99', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1209279_3-yakult-probiotic-health-drink.jpg', '0000-00-00 00:00:00'),
(52, 'Fruit Juice - Mixed Fruit Delight', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '129.89', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1206500_2-tropicana-fruit-juice-mixed-fruit-delight.jpg', '0000-00-00 00:00:00'),
(53, 'Soft Drink', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '399.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1212277_1-sprite-soft-drink.jpg', '0000-00-00 00:00:00'),
(54, 'Instant Coffee', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '306.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/266579_20-bru-instant-coffee.jpg', '0000-00-00 00:00:00'),
(55, 'Coconut Water - Refreshing Flavour, Vital Electrolytes', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '246.51', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1206628_5-paper-boat-coconut-water-refreshing-flavour-vital-electrolytes.jpg', '0000-00-00 00:00:00'),
(56, 'Health & Nutrition Drink - Classic Malt', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '408.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/119385_11-horlicks-health-nutrition-drink-classic-malt.jpg', '0000-00-00 00:00:00'),
(57, 'Gluco Biscuits - Parle-G', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '62.37', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/102102_4-parle-gluco-biscuits-parle-g.jpg', '0000-00-00 00:00:00'),
(58, 'Bourbon Cream Biscuit - Chocolate Flavor', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '44.56', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1201309_2-britannia-bourbon-cream-biscuit-chocolate-flavor.jpg', '0000-00-00 00:00:00'),
(59, 'Oats', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '208.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/284405_11-quaker-oats.jpg', '0000-00-00 00:00:00'),
(60, 'Noodles - Masala 280 gm + Ketchup Tomato 1 kg', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '192.54', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200218_1-maggi-noodles-masala-280-gm-ketchup-tomato-1-kg.jpg', '0000-00-00 00:00:00'),
(61, 'Fresh Tomato Ketchup', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '105.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40029538_31-kissan-fresh-tomato-ketchup.jpg', '0000-00-00 00:00:00'),
(62, 'Good Day Cashew Cookies', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '87.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40083744_4-britannia-good-day-cashew-cookies.jpg', '0000-00-00 00:00:00'),
(63, 'Potato Chips - Calm Cream & Onion Flavour', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '9.90', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/294297_12-lays-potato-chips-calm-cream-onion-flavour.jpg', '0000-00-00 00:00:00'),
(64, 'Potato Chips - American Style Cream & Onion Flavour', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '18.81', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/102745_9-lays-potato-chips-american-style-cream-onion-flavour.jpg', '0000-00-00 00:00:00'),
(65, 'Biscuits - Marie Gold', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '51.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1201303_2-britannia-biscuits-marie-gold.jpg', '0000-00-00 00:00:00'),
(66, 'Nutri-licious Masala Veg Atta Noodles - Pouch', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '80.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/266096_22-maggi-nutri-licious-masala-veg-atta-noodles-pouch.jpg', '0000-00-00 00:00:00'),
(67, 'Chocolate', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '100.86', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200590_3-cadbury-dairy-milk-chocolate.jpg', '0000-00-00 00:00:00'),
(68, 'Hakka Noodles - Veg', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '64.35', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40141483_1-desi-hakka-noodles-veg.jpg', '0000-00-00 00:00:00'),
(69, 'Hide & Seek Chocolate', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '28.22', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/302121_14-parle-hide-seek-chocolate.jpg', '0000-00-00 00:00:00'),
(70, 'Chocos', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '132.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/122650_7-kelloggs-chocos.jpg', '0000-00-00 00:00:00'),
(71, 'Eggs - Free Range', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '208.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40117922_2-farm-made-eggs-free-range.jpg', '0000-00-00 00:00:00'),
(72, 'Chicken Curry Cut - With Skin, Antibiotic Residue-Free, Growth Hormone-Free, 12-14 pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '108.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000926_9-fresho-chicken-curry-cut-with-skin-antibiotic-residue-free-growth-hormone-free-12-14-pcs.jpg', '0000-00-00 00:00:00'),
(73, 'Rohu Fish - Large, Curry Cut/Bengali Cut, Preservative Free, 12-15 pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '449.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000756_34-fresho-rohu-fish-large-curry-cutbengali-cut-preservative-free-12-15-pcs.jpg', '0000-00-00 00:00:00'),
(74, 'Eggs - Free Range', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '119.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40092369_6-farm-made-eggs-free-range.jpg', '0000-00-00 00:00:00'),
(75, 'Mixed Chicken Pieces - Boneless, Antibiotic Residue-Free, Growth Hormone-Free, 4-6 pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '298.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000924_11-fresho-mixed-chicken-pieces-boneless-antibiotic-residue-free-growth-hormone-free-4-6-pcs.jpg', '0000-00-00 00:00:00'),
(76, 'Catla Fish - Large, Curry Cut/Bengali Cut, Preservative Free, 12-15 pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '599.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000755_27-fresho-catla-fish-large-curry-cutbengali-cut-preservative-free-12-15-pcs.jpg', '0000-00-00 00:00:00');
INSERT INTO `products` (`id`, `name`, `desc`, `price`, `rrp`, `quantity`, `img`, `date_added`) VALUES
(77, 'Farm Eggs - Brown, Medium, Antibiotic Residue-Free, Growth Hormone-Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '75.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40038379_6-fresho-farm-eggs-brown-medium-antibiotic-residue-free-growth-hormone-free.jpg', '0000-00-00 00:00:00'),
(78, 'Basa Fish Fillet - Preservative Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '699.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40048878_2-fresho-basa-fish-fillet-preservative-free.jpg', '0000-00-00 00:00:00'),
(79, 'Chicken Mince - Antibiotic Residue Free, Growth Hormone-Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '199.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000906_9-fresho-chicken-mince-antibiotic-residue-free-growth-hormone-free.jpg', '0000-00-00 00:00:00'),
(80, 'White Prawns - Medium, Unpeeled, 30-40 pcs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '499.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000971_13-fresho-white-prawns-medium-unpeeled-30-40-pcs.jpg', '0000-00-00 00:00:00'),
(81, 'Chicken Liver - Antibiotic Residue-Free, Growth Hormone-Free', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '84.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/10000916_11-fresho-chicken-liver-antibiotic-residue-free-growth-hormone-free.jpg', '0000-00-00 00:00:00'),
(82, 'Eggs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '74.25', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40106728_5-ayur-plus-eggs.jpg', '0000-00-00 00:00:00'),
(83, 'Healthy Brown Eggs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '74.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40161158_2-upf-healthy-brown-eggs.jpg', '0000-00-00 00:00:00'),
(84, 'Healthy Daily Eggs', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '64.35', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40161157_2-upf-healthy-daily-eggs.jpg', '0000-00-00 00:00:00'),
(85, 'Ragi Sticks - Achari Masala', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '70.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208395_5-gooddiet-ragi-sticks-achari-masala.jpg', '0000-00-00 00:00:00'),
(86, 'Olive Oil - Extra Virgin', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '664.05', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40016670_7-disano-olive-oil-extra-virgin.jpg', '0000-00-00 00:00:00'),
(87, '100% Natural Cold Pressed Juice - Valencia Orange', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '912.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1212124_1-raw-pressery-100-natural-cold-pressed-juice-valencia-orange.jpg', '0000-00-00 00:00:00'),
(88, 'Greek Yogurt - Natural', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '178.20', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200551_3-epigamia-greek-yogurt-natural.jpg', '0000-00-00 00:00:00'),
(89, 'Durum Wheat Pasta - Fusilli', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '125.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/303129_1-borges-durum-wheat-pasta-fusilli.jpg', '0000-00-00 00:00:00'),
(90, 'Greek Yogurt - Alphonso Mango', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '178.20', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200550_3-epigamia-greek-yogurt-alphonso-mango.jpg', '0000-00-00 00:00:00'),
(91, 'Multigrain Puffs - Butter Makhana', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '70.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208398_5-gooddiet-multigrain-puffs-butter-makhana.jpg', '0000-00-00 00:00:00'),
(92, 'Coconut Milk - UHT Natural', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '266.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1200391_2-kara-coconut-milk-uht-natural.jpg', '0000-00-00 00:00:00'),
(93, 'Nacho Crisps - Peri Peri', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '33.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40071518_4-cornitos-nacho-crisps-peri-peri.jpg', '0000-00-00 00:00:00'),
(94, 'Multigrain Puffs - Tangy Tomato', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '70.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208402_4-gooddiet-multigrain-puffs-tangy-tomato.jpg', '0000-00-00 00:00:00'),
(95, 'Durum Wheat Pasta - Spaghetti', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '105.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/303124_4-borges-durum-wheat-pasta-spaghetti.jpg', '0000-00-00 00:00:00'),
(96, 'Greek Yogurt - Blueberry', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '356.40', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1212334_1-epigamia-greek-yogurt-blueberry.jpg', '0000-00-00 00:00:00'),
(97, 'Gold Blend Instant Coffee Powder - Rich & Smooth', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '855.00', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/40154924_2-nescafe-gold-blend-instant-coffee-powder-rich-smooth.jpg', '0000-00-00 00:00:00'),
(98, 'Multigrain Bread Chips - Chilli Orange', '<p>At Cure Grocery Store, we guarantee you the perfect maintenance of hygiene ensured throughout the delivery of your products. Each product is assured to be of best of the quality and true to the quantity. (Please note: the delivery of the products might take 2-3 business days. </p> <h3>Points</h3><ul><li>Product may slightly differ from the displayed picture</li><li>Made in India </li><li>Questions about the product? Contact us and we?ll get back to you!</li></ul>', '70.99', '0.00', 15, 'https://www.bigbasket.com/media/uploads/p/s/1208403_4-gooddiet-multigrain-bread-chips-chilli-orange.jpg', '0000-00-00 00:00:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=99;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
